import { EditorialPage } from '@/components/editorial-page';

export const dynamic = 'force-static';

export default function PredictiveArchitecture() {
  return <EditorialPage
    category="MCAE / Prediction"
    title="Predictive architecture: modelling readiness without pretending certainty"
    intro="A useful prediction does more than count activity. It weighs what happened, how reliable the signal is, when it happened and what was changing around the person at the time."
    backHref="/solutions" backLabel="All solutions"
    nextHref="/solutions/self-healing-systems" nextLabel="Self-healing systems"
    sections={[
      { heading: 'Activity is not the same as intent', paragraphs: ['MCAE can observe frequency, recency and interaction at scale, but observation alone does not establish motivation. An email open may come from a person, a security scanner or a privacy feature. A download may signal research, curiosity or genuine commercial urgency.', 'Predictive architecture begins by asking how much confidence each signal deserves. Weak evidence can still be useful, but it should never be allowed to carry the authority of a deliberate reply, form submission or sales conversation.'], quote: 'The aim is not to reward activity. It is to approximate readiness with evidence the organisation can defend.' },
      { heading: 'Time changes the meaning of a score', paragraphs: ['A lifetime score is a record of history, not a statement of present intent. Someone who engaged heavily last year is not equivalent to someone showing sustained interest this week, even when their totals match.', 'Every meaningful signal therefore needs an appropriate half-life. A contract window, event registration and pricing-page visit each rise and fade at different rates. Degradation keeps the model responsive to momentum instead of allowing old behaviour to harden into permanent priority.'] },
      { heading: 'Fit has stable and changing parts', paragraphs: ['Profile grading answers a different question: is this person and organisation structurally suited to what is being offered? Role, sector and organisational scale may remain fairly stable, while product need, opportunity status or recent experience can change quickly.', 'DCC separates those durable and temporary truths. Match, mismatch and unknown are treated as different states, and short-lived relevance is allowed to expire. That creates profiles which can become more precise without becoming falsely permanent.'] },
      { heading: 'Buying context travels through relationships', paragraphs: ['Commercial decisions rarely sit with one person. Subsidiaries share experience, colleagues compare notes and activity in one division can change the appetite of another. A model that scores every prospect as an isolated unit misses this transfer of confidence and concern.', 'Relevant account and relationship events can be structured in Salesforce and made legible to MCAE. This is where community thinking becomes technical design: the model recognises that people act within networks, while still requiring an explicit and auditable signal before the system responds.'] },
      { heading: 'Segmentation should express the model', paragraphs: ['Campaign lists should not become a parallel universe of one-off assumptions. When readiness, fit and source-of-truth rules are properly defined, useful audiences emerge from the architecture itself.'], list: ['Dynamic audiences that reflect current conditions', 'Journeys matched to both fit and timing', 'Less manual list maintenance', 'Clearer reasons for inclusion, exclusion and hand-off'] },
      { heading: 'Prediction should remain honest', paragraphs: ['A score is a probability, not a verdict. Where the evidence is incomplete, the system should expose uncertainty rather than manufacture confidence. That distinction protects prospects from inappropriate treatment and gives commercial teams a better basis for judgement.', 'Prediction identifies a plausible opportunity. The observation layer then checks whether the evidence still holds. Together they turn qualification from a one-time label into a disciplined, changing assessment.'], quote: 'Identify readiness. Preserve uncertainty. Reassess as reality changes.' },
    ]}
  />;
}
