import { EditorialPage } from '@/components/editorial-page';

export const dynamic = 'force-static';

export default function PredictiveArchitecture() {
  return <EditorialPage
    category="MCAE / Prediction"
    title="Predictive architecture: judging readiness without claiming certainty"
    intro="A useful prediction goes beyond activity totals. It considers the event, the reliability of the signal, its age and the circumstances around the person at the time."
    backHref="/solutions" backLabel="All solutions"
    nextHref="/solutions/self-healing-systems" nextLabel="Self-healing systems"
    sections={[
      { heading: 'Activity is not the same as intent', paragraphs: ['MCAE can observe frequency, recency and interaction at scale, but observation alone does not establish motivation. An email open may come from a person, a security scanner or a privacy feature. A download may signal research, curiosity or genuine commercial urgency.', 'Predictive architecture starts by deciding how much confidence each signal deserves. Weak evidence can be useful, but it should not carry the same authority as a deliberate reply, form submission or sales conversation.'], quote: 'Scoring should measure readiness using evidence the organisation can defend.' },
      { heading: 'Time changes the meaning of a score', paragraphs: ['A lifetime score records history; it does not prove current intent. Someone who engaged heavily last year is not equivalent to someone showing sustained interest this week, even when their totals match.', 'Every meaningful signal needs an appropriate half-life. A contract window, event registration and pricing-page visit remain relevant for different lengths of time. Planned degradation keeps the model responsive to current momentum and prevents old behaviour from becoming a permanent priority.'] },
      { heading: 'Fit has stable and changing parts', paragraphs: ['Profile grading answers a different question: is this person and organisation structurally suited to what is being offered? Role, sector and organisational scale may remain fairly stable, while product need, opportunity status or recent experience can change quickly.', 'DCC keeps durable attributes separate from temporary ones. Match, mismatch and unknown each have a defined meaning, and short-lived relevance is allowed to expire. Profiles can then become more precise without turning a temporary situation into a permanent classification.'] },
      { heading: 'Buying context travels through relationships', paragraphs: ['Commercial decisions rarely sit with one person. Subsidiaries share experience, colleagues compare notes and activity in one division can change the appetite of another. A model that scores every prospect as an isolated unit misses this transfer of confidence and concern.', 'Relevant account and relationship events can be structured in Salesforce and made legible to MCAE. Here, community thinking becomes technical design. The model recognises that people act within networks, but still requires an explicit and auditable signal before responding.'] },
      { heading: 'Segmentation should express the model', paragraphs: ['Campaign lists should not become a parallel universe of one-off assumptions. When readiness, fit and source-of-truth rules are properly defined, useful audiences emerge from the architecture itself.'], list: ['Dynamic audiences that reflect current conditions', 'Journeys matched to both fit and timing', 'Less manual list maintenance', 'Clearer reasons for inclusion, exclusion and hand-off'] },
      { heading: 'Prediction should remain honest', paragraphs: ['A score indicates probability. It is not a verdict. Where the evidence is incomplete, the system should show that uncertainty. This protects prospects from inappropriate treatment and gives commercial teams a better basis for judgement.', 'Prediction identifies a plausible opportunity, and the observation layer checks whether the evidence still holds. Qualification becomes an assessment that can change instead of a label applied once and left in place.'], quote: 'A useful prediction shows both the likely opportunity and the limits of the evidence.' },
    ]}
  />;
}
